version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: inventorymanagement-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-INVENTORYMANAGEMENT}
    volumes:
      - ./postgres-data:/var/lib/postgresql